version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: illuvrse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6380:6379'

  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      MEILI_NO_ANALYTICS: 'true'
    ports:
      - '7700:7700'

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env
    ports:
      - '${API_PORT:-4100}:${API_PORT:-4100}'
    depends_on:
      - postgres
      - redis
      - meilisearch

  workers:
    build:
      context: .
      dockerfile: workers/Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  postgres_data:
