import { Queue, Worker } from 'bullmq';
import Parser from 'rss-parser';
import { Prisma, PrismaClient, ShowType, SourceCategory } from '@prisma/client';
import { contentHashFromText, normalizeUrl } from '../../../lib/pipeline/canonicalize';
import { shouldJoinCluster } from '../../../lib/pipeline/dedupCluster';
import { summarizeCluster } from '../../../lib/pipeline/summarize';
import { computeClusterScore } from '../../../lib/ranking/score';
import { invalidateCached } from '../../../lib/ranking/cache';
import { generatePodcastScript, VoiceMode } from '../../../lib/podcast/template';
import { uploadAudioBuffer } from '../services/storage';
import { evaluateClusterQuality } from '../../../lib/evaluation/clusterQuality';
import { evaluateSummaryQuality } from '../../../lib/evaluation/summaryQuality';
import { calculateRankingDrift } from '../../../lib/evaluation/rankingDrift';
import { scoreSourceHealth } from '../../../lib/reputation/sourceHealth';
import { buildInterestVector } from '../../../lib/personalization/interestVector';
import { assignVariant } from '../../../lib/experiments/assignment';
import { estimateCost, shouldSkipByBudget } from '../../../lib/cost/tokenBudget';
import { embedTextStub } from '../../../lib/search/semantic';
import { buildVerticalIntelligence, isGamingCluster } from '../../../lib/vertical-intelligence/gamingSignals';
import { retryWithBackoff } from '../../../lib/pipeline/retry';
import { getBootstrapJobs } from '../utils/bootstrapJobs';

const redisUrl = new URL(process.env.REDIS_URL ?? 'redis://localhost:6379');
const connection = {
  host: redisUrl.hostname,
  port: Number(redisUrl.port || 6379),
  username: redisUrl.username || undefined,
  password: redisUrl.password || undefined,
  maxRetriesPerRequest: null as null
};
const prisma = new PrismaClient();
const parser = new Parser();

const canonicalizeQueue = new Queue('canonicalize_queue', { connection });
const dedupQueue = new Queue('dedup_cluster_queue', { connection });
const summarizeQueue = new Queue('summarize_cluster_queue', { connection });
const evaluationQueue = new Queue('evaluation_queue', { connection });
const rankQueue = new Queue('rank_queue', { connection });
const ttsQueue = new Queue('tts_queue', { connection });
const sourceReputationQueue = new Queue('source_reputation_queue', { connection });
const personalizationQueue = new Queue('personalization_queue', { connection });

async function log(queue: string, status: string, payload: unknown): Promise<void> {
  await prisma.pipelineLog.create({ data: { queue, status, payload: payload as object } });
}

async function logTokens(stage: string, tokensUsed: number): Promise<void> {
  await prisma.tokenUsageLog.create({
    data: {
      pipelineStage: stage,
      tokensUsed,
      costEstimate: estimateCost(tokensUsed)
    }
  });
}

async function createTask(title: string, description: string): Promise<void> {
  const existing = await prisma.taskCard.findFirst({ where: { title, status: { in: ['open', 'in_progress'] } } });
  if (!existing) {
    await prisma.taskCard.create({ data: { title, description, autoGenerated: true } });
  }
}

function textFromArticle(article: { title: string; extractedText: string | null }): string {
  return [article.title, article.extractedText ?? ''].join(' ').trim();
}

function mapShowTypeToMode(showType: ShowType): VoiceMode {
  if (showType === 'deep_dive' || showType === 'weekly_vertical') {
    return 'analyst';
  }
  if (showType === 'weekly_global') {
    return 'debate';
  }
  if (showType === 'daily_local' || showType === 'weekly_local') {
    return 'rapid';
  }
  return 'solo';
}

export function createWorkers() {
  const ingestWorker = new Worker(
    'ingest_queue',
    async (job) => {
      const { sourceId, rssUrl } = job.data as { sourceId: string; rssUrl: string };
      const feed = await retryWithBackoff(
        () => parser.parseURL(rssUrl),
        { attempts: 3, baseDelayMs: 300, maxDelayMs: 2_000 }
      );
      const items = feed.items?.slice(0, 25) ?? [];

      for (const item of items) {
        if (!item.link || !item.title) {
          continue;
        }

        const article = await prisma.article.upsert({
          where: { url: item.link },
          update: {
            title: item.title,
            author: item.creator,
            publishedAt: item.isoDate ? new Date(item.isoDate) : new Date(),
            extractedText: item.contentSnippet ?? item.content ?? item.title
          },
          create: {
            sourceId,
            title: item.title,
            author: item.creator,
            url: item.link,
            publishedAt: item.isoDate ? new Date(item.isoDate) : new Date(),
            rawHtml: item.content ?? null,
            extractedText: item.contentSnippet ?? item.content ?? item.title
          }
        });

        await canonicalizeQueue.add('canonicalize-article', {
          articleId: article.id,
          url: article.url,
          extractedText: article.extractedText ?? article.title
        });
      }

      await log('ingest_queue', 'processed', { sourceId, itemCount: items.length });
    },
    { connection }
  );

  const canonicalizeWorker = new Worker(
    'canonicalize_queue',
    async (job) => {
      const { articleId, url, extractedText } = job.data as { articleId: string; url: string; extractedText: string };
      const canonicalUrl = normalizeUrl(url);
      const contentHash = contentHashFromText(extractedText);
      await prisma.article.update({
        where: { id: articleId },
        data: {
          canonicalUrl,
          contentHash
        }
      });
      await dedupQueue.add('dedup-article', { articleId });
      await log('canonicalize_queue', 'processed', job.data);
    },
    { connection }
  );

  const dedupWorker = new Worker(
    'dedup_cluster_queue',
    async (job) => {
      const { articleId } = job.data as { articleId: string };
      const article = await prisma.article.findUnique({ where: { id: articleId } });
      if (!article || !article.contentHash || !article.canonicalUrl) {
        await log('dedup_cluster_queue', 'skipped', job.data);
        return;
      }

      const candidates = await prisma.cluster.findMany({
        where: {
          updatedAt: {
            gte: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
          }
        },
        orderBy: { updatedAt: 'desc' },
        take: 300,
        include: {
          articles: {
            take: 1,
            orderBy: {
              article: {
                publishedAt: 'desc'
              }
            },
            include: {
              article: true
            }
          }
        }
      });

      const joined = candidates.find((cluster) => {
        const sample = cluster.articles[0]?.article;
        if (!sample || !sample.canonicalUrl) {
          return false;
        }

        return shouldJoinCluster({
          canonicalUrlA: article.canonicalUrl ?? '',
          canonicalUrlB: sample.canonicalUrl,
          contentA: textFromArticle(article),
          contentB: textFromArticle(sample),
          threshold: 0.35
        });
      });

      const clusterId =
        joined?.id ??
        (
          await prisma.cluster.create({
            data: {
              title: article.title,
              summaryBullets: [],
              whyItMatters: [],
              citations: [article.url],
              storyVector: embedTextStub(article.title)
            }
          })
        ).id;

      await prisma.clusterArticle.upsert({
        where: {
          clusterId_articleId: {
            clusterId,
            articleId: article.id
          }
        },
        update: {},
        create: { clusterId, articleId: article.id }
      });

      await summarizeQueue.add('summarize-cluster', { clusterId });
      await rankQueue.add('rank-cluster', { clusterId });
      await evaluationQueue.add('evaluate-cluster', { entityType: 'cluster', clusterId });
      await log('dedup_cluster_queue', 'processed', { clusterId, articleId });
    },
    { connection }
  );

  const summarizeWorker = new Worker(
    'summarize_cluster_queue',
    async (job) => {
      const { clusterId } = job.data as { clusterId: string };
      const cluster = await prisma.cluster.findUnique({
        where: { id: clusterId },
        include: {
          articles: {
            include: {
              article: {
                include: {
                  source: true
                }
              }
            }
          }
        }
      });

      if (!cluster) {
        return;
      }

      if (cluster.articles.length < 2) {
        await log('summarize_cluster_queue', 'skipped-small-cluster', job.data);
        return;
      }

      const latestSummaryEval = await prisma.evaluationLog.findFirst({
        where: { entityType: 'summary', entityId: clusterId },
        orderBy: { createdAt: 'desc' }
      });
      if (latestSummaryEval && latestSummaryEval.createdAt >= cluster.updatedAt) {
        await log('summarize_cluster_queue', 'skipped-unchanged', job.data);
        return;
      }

      const summary = summarizeCluster(
        cluster.articles.map((entry) => ({
          title: entry.article.title,
          url: entry.article.url,
          category: entry.article.source.category as SourceCategory
        }))
      );
      const estimatedTokens = summary.whatHappened.join(' ').split(/\s+/).length * 2;
      await logTokens('summarize_cluster_queue', estimatedTokens);
      if (shouldSkipByBudget('summarize_cluster_queue', estimatedTokens)) {
        await createTask('Summarization budget spike', `Cluster ${clusterId} exceeded summarization token budget.`);
        return;
      }

      const gaming = isGamingCluster(cluster.title, summary.whatHappened);
      const verticalIntel = gaming ? buildVerticalIntelligence(cluster.title) : null;

      await prisma.cluster.update({
        where: { id: cluster.id },
        data: {
          summaryBullets: summary.whatHappened,
          whyItMatters: summary.whyItMatters,
          localAngle: summary.localAngle ?? Prisma.JsonNull,
          verticalAngle: summary.verticalAngle ?? Prisma.JsonNull,
          citations: summary.citations,
          storyVector: embedTextStub([cluster.title, ...summary.whatHappened].join(' ')),
          builderTakeaway: verticalIntel?.builderTakeaway,
          monetizationImpact: verticalIntel?.monetizationImpact,
          platformImplications: verticalIntel?.platformImplications
        }
      });

      await evaluationQueue.add('evaluate-summary', { entityType: 'summary', clusterId });
      await log('summarize_cluster_queue', 'processed', job.data);
    },
    { connection }
  );

  const evaluationWorker = new Worker(
    'evaluation_queue',
    async (job) => {
      const data = job.data as { entityType: 'cluster' | 'summary' | 'ranking'; clusterId?: string; topIds?: string[] };

      if (data.entityType === 'cluster' && data.clusterId) {
        const cluster = await prisma.cluster.findUnique({
          where: { id: data.clusterId },
          include: { articles: { include: { article: true } } }
        });
        if (!cluster) {
          return;
        }

        const sourceCount = new Set(cluster.articles.map((item) => item.article.sourceId)).size;
        const similaritySpread = Math.min(1, Math.max(0, (cluster.articles.length - sourceCount) / Math.max(1, cluster.articles.length)));
        const result = evaluateClusterQuality({
          articleCount: cluster.articles.length,
          sourceCount,
          similaritySpread
        });

        await prisma.evaluationLog.create({
          data: {
            entityType: 'cluster',
            entityId: cluster.id,
            score: result.score,
            metadata: result.metadata
          }
        });

        if (result.score < 0.4) {
          await createTask('Cluster quality regression', `Cluster ${cluster.id} scored ${result.score}.`);
        }
      }

      if (data.entityType === 'summary' && data.clusterId) {
        const cluster = await prisma.cluster.findUnique({ where: { id: data.clusterId } });
        if (!cluster) {
          return;
        }
        const bullets = Array.isArray(cluster.summaryBullets) ? (cluster.summaryBullets as string[]) : [];
        const why = Array.isArray(cluster.whyItMatters) ? (cluster.whyItMatters as string[]) : [];
        const citations = Array.isArray(cluster.citations) ? (cluster.citations as string[]) : [];
        const result = evaluateSummaryQuality({ bullets, whyItMatters: why, citations });

        await prisma.evaluationLog.create({
          data: {
            entityType: 'summary',
            entityId: cluster.id,
            score: result.score,
            metadata: result.metadata
          }
        });

        if (result.score < 0.45) {
          await createTask('Summary quality regression', `Summary for cluster ${cluster.id} scored ${result.score}.`);
        }
      }

      if (data.entityType === 'ranking') {
        const currentTop = data.topIds ?? [];
        const latest = await prisma.evaluationLog.findFirst({
          where: { entityType: 'ranking', entityId: 'global-top20' },
          orderBy: { createdAt: 'desc' }
        });
        const previousTop = latest && typeof latest.metadata === 'object' && latest.metadata && 'topIds' in latest.metadata
          ? (latest.metadata as { topIds?: string[] }).topIds ?? []
          : [];
        const drift = calculateRankingDrift(previousTop, currentTop);

        await prisma.evaluationLog.create({
          data: {
            entityType: 'ranking',
            entityId: 'global-top20',
            score: drift.score,
            metadata: { changedPositions: drift.changedPositions, topIds: currentTop }
          }
        });

        if (drift.score > 0.55) {
          await createTask('Ranking drift alert', `Top rankings drift score reached ${drift.score}.`);
        }
      }

      await log('evaluation_queue', 'processed', data);
    },
    { connection }
  );

  const rankWorker = new Worker(
    'rank_queue',
    async (job) => {
      const { clusterId } = job.data as { clusterId: string };
      const cluster = await prisma.cluster.findUnique({
        where: { id: clusterId },
        include: {
          articles: {
            include: {
              article: {
                include: {
                  source: {
                    include: { metrics: true }
                  }
                }
              }
            }
          }
        }
      });

      if (!cluster || cluster.articles.length === 0) {
        return;
      }

      const publishedAt = cluster.articles
        .map((entry) => entry.article.publishedAt)
        .sort((a, b) => b.getTime() - a.getTime())[0];
      if (!publishedAt) {
        return;
      }

      const uniqueSources = new Set(cluster.articles.map((entry) => entry.article.sourceId)).size;
      const categories = new Set(cluster.articles.map((entry) => entry.article.source.category));
      const reputationValues = cluster.articles
        .map((entry) => entry.article.source.metrics?.accuracyScore ?? 0.6)
        .filter((value) => value >= 0);
      const sourceReputation =
        reputationValues.reduce((sum, value) => sum + value, 0) / Math.max(1, reputationValues.length);

      const globalScore = computeClusterScore({
        publishedAt,
        sourceDiversity: uniqueSources,
        articleCount: cluster.articles.length,
        category: 'global',
        sourceReputation
      });

      const verticalScore = computeClusterScore({
        publishedAt,
        sourceDiversity: uniqueSources,
        articleCount: cluster.articles.length,
        category: categories.has('vertical') ? 'vertical' : 'global',
        sourceReputation
      });

      const localScore = computeClusterScore({
        publishedAt,
        sourceDiversity: uniqueSources,
        articleCount: cluster.articles.length,
        category: categories.has('local') ? 'local' : 'global',
        sourceReputation
      });

      await prisma.cluster.update({ where: { id: clusterId }, data: { globalScore, verticalScore, localScore } });
      invalidateCached('global:');
      invalidateCached('vertical:');
      invalidateCached('local:');

      const topGlobal = await prisma.cluster.findMany({ orderBy: { globalScore: 'desc' }, select: { id: true }, take: 20 });
      await evaluationQueue.add('evaluate-ranking', {
        entityType: 'ranking',
        topIds: topGlobal.map((item) => item.id)
      });
      await log('rank_queue', 'processed', job.data);
    },
    { connection }
  );

  const sourceReputationWorker = new Worker(
    'source_reputation_queue',
    async () => {
      const sources = await prisma.source.findMany({ include: { articles: true } });
      for (const source of sources) {
        const urls = source.articles.map((article) => article.canonicalUrl ?? article.url);
        const duplicateRate = urls.length === 0 ? 0 : 1 - new Set(urls).size / urls.length;
        const averageLagHours = source.articles.length === 0
          ? 24
          : source.articles
              .map((article) => Math.abs(Date.now() - article.publishedAt.getTime()) / (1000 * 60 * 60))
              .reduce((sum, value) => sum + value, 0) / source.articles.length;

        const health = scoreSourceHealth({ duplicateRate, averageLagHours, sourceDiversity: source.articles.length });

        await prisma.sourceMetrics.upsert({
          where: { sourceId: source.id },
          update: {
            accuracyScore: health.accuracyScore,
            recencyScore: health.recencyScore,
            diversityScore: health.diversityScore,
            biasScore: health.biasScore,
            lastEvaluatedAt: new Date()
          },
          create: {
            sourceId: source.id,
            accuracyScore: health.accuracyScore,
            recencyScore: health.recencyScore,
            diversityScore: health.diversityScore,
            biasScore: health.biasScore,
            lastEvaluatedAt: new Date()
          }
        });

        if (health.aggregate < 0.4) {
          await createTask('Source reliability drop', `Source ${source.name} aggregate score dropped to ${health.aggregate}.`);
        }
      }

      await log('source_reputation_queue', 'processed', { sourceCount: sources.length });
    },
    { connection }
  );

  const personalizationWorker = new Worker(
    'personalization_queue',
    async () => {
      const users = await prisma.user.findMany({
        include: {
          interactions: {
            include: {
              cluster: true
            },
            orderBy: { createdAt: 'desc' },
            take: 300
          }
        }
      });

      for (const user of users) {
        const records = user.interactions.map((interaction) => {
          const scoreTriplet = [interaction.cluster.globalScore, interaction.cluster.verticalScore, interaction.cluster.localScore];
          const max = Math.max(...scoreTriplet);
          const category: 'global' | 'vertical' | 'local' =
            max === interaction.cluster.verticalScore ? 'vertical' : max === interaction.cluster.localScore ? 'local' : 'global';

          return {
            interactionType: interaction.interactionType,
            clusterCategory: category
          };
        });

        const vector = buildInterestVector(records);
        await prisma.user.update({ where: { id: user.id }, data: { interestVector: vector } });
      }

      await log('personalization_queue', 'processed', { userCount: users.length });
    },
    { connection }
  );

  const experimentEvalWorker = new Worker(
    'experiment_evaluation_queue',
    async () => {
      const experiments = await prisma.experiment.findMany({ where: { active: true } });
      for (const experiment of experiments) {
        const users = await prisma.user.findMany({ take: 50, select: { id: true } });
        for (const user of users) {
          const variant = assignVariant(user.id, experiment.id);
          const exists = await prisma.experimentAssignment.findFirst({ where: { userId: user.id, experimentId: experiment.id } });
          if (!exists) {
            await prisma.experimentAssignment.create({
              data: { userId: user.id, experimentId: experiment.id, variant }
            });
          }
        }
      }

      await log('experiment_evaluation_queue', 'processed', { experimentCount: experiments.length });
    },
    { connection }
  );

  const scriptWorker = new Worker(
    'podcast_script_queue',
    async (job) => {
      const { showType } = job.data as { showType: ShowType };
      const mode = mapShowTypeToMode(showType);
      const orderBy =
        showType === 'daily_vertical' || showType === 'weekly_vertical'
          ? { verticalScore: 'desc' as const }
          : showType === 'daily_local' || showType === 'weekly_local'
            ? { localScore: 'desc' as const }
            : { globalScore: 'desc' as const };

      const clusters = await prisma.cluster.findMany({ orderBy, take: 5 });
      const scripted = generatePodcastScript({
        showTitle: showType,
        mode,
        sponsorSlot: 'Dynamic sponsor slot placeholder',
        stories: clusters.map((cluster) => ({
          title: cluster.title,
          summary: Array.isArray(cluster.summaryBullets) ? cluster.summaryBullets.join(' ') : 'Summary unavailable.',
          sources: (cluster.citations as string[]) ?? []
        }))
      });

      const estimatedTokens = scripted.script.split(/\s+/).length;
      await logTokens('podcast_script_queue', estimatedTokens);
      if (shouldSkipByBudget('podcast_script_queue', estimatedTokens)) {
        await createTask('Podcast script budget spike', `Show ${showType} exceeded token budget.`);
        return;
      }

      const template = await prisma.podcastTemplate.findFirst({ where: { name: mode === 'debate' ? 'debate-duo' : mode === 'analyst' ? 'analyst-deep-dive' : mode === 'rapid' ? 'rapid-fire' : 'solo-brief' } });

      const episode = await prisma.episode.create({
        data: {
          showType,
          title: `${showType} - ${new Date().toISOString().slice(0, 10)}`,
          description: 'Auto-generated by ILLUVRSE pipeline.',
          audioUrl: '',
          durationSeconds: 0,
          publishedAt: new Date(),
          rssGuid: `${showType}-${Date.now()}`,
          templateId: template?.id,
          voiceMode: mode
        }
      });

      await ttsQueue.add('tts-episode', {
        episodeId: episode.id,
        script: scripted.script,
        segments: scripted.segments,
        voices: mode === 'debate' ? ['Host Alpha', 'Host Beta'] : mode === 'analyst' ? ['Analyst'] : ['Narrator']
      });

      await log('podcast_script_queue', 'processed', { ...job.data, episodeId: episode.id });
      return { episodeId: episode.id, script: scripted.script };
    },
    { connection }
  );

  const ttsWorker = new Worker(
    'tts_queue',
    async (job) => {
      const data = job.data as { episodeId: string; script: string; segments?: Array<{ speaker: string; text: string }>; voices?: string[] };
      const segments = data.segments ?? [{ speaker: 'Narrator', text: data.script }];
      const rendered = segments.map((segment) => `[${segment.speaker}] ${segment.text}`).join('\n');
      const audioData = Buffer.from(rendered, 'utf8');
      const uploaded = await retryWithBackoff(
        () => uploadAudioBuffer(data.episodeId, audioData),
        { attempts: 3, baseDelayMs: 500, maxDelayMs: 2_500 }
      );
      await prisma.episode.update({
        where: { id: data.episodeId },
        data: {
          audioUrl: uploaded.audioUrl,
          durationSeconds: uploaded.durationSeconds
        }
      });
      await log('tts_queue', 'processed', { episodeId: data.episodeId, voiceCount: data.voices?.length ?? 1 });
    },
    { connection }
  );

  const rssPublishWorker = new Worker(
    'rss_publish_queue',
    async (job) => {
      await log('rss_publish_queue', 'processed', job.data);
    },
    { connection }
  );

  const weeklyDigestWorker = new Worker(
    'weekly_digest_queue',
    async () => {
      const now = new Date().toISOString().slice(0, 10);
      const topGlobal = await prisma.cluster.findMany({ orderBy: { globalScore: 'desc' }, take: 10 });
      const topVertical = await prisma.cluster.findMany({ orderBy: { verticalScore: 'desc' }, take: 10 });
      const topLocal = await prisma.cluster.findMany({ orderBy: { localScore: 'desc' }, take: 10 });

      const markdown = [
        `# Weekly Global Brief (${now})`,
        ...topGlobal.map((item) => `- ${item.title}`),
        `\n# Weekly ILLUVRSE Industry Report`,
        ...topVertical.map((item) => `- ${item.title}`),
        `\n# Weekly Chicago Digest`,
        ...topLocal.map((item) => `- ${item.title}`)
      ].join('\n');

      const html = `<h1>Weekly Reports ${now}</h1><h2>Global</h2><ul>${topGlobal.map((item) => `<li>${item.title}</li>`).join('')}</ul>`;

      await logTokens('weekly_digest_queue', markdown.split(/\s+/).length * 2);
      await prisma.pipelineLog.create({
        data: {
          queue: 'weekly_digest_queue',
          status: 'exported',
          payload: { markdown, html }
        }
      });

      await prisma.episode.createMany({
        data: [
          { showType: 'weekly_global', title: `Weekly Global ${now}`, description: 'Weekly global digest', audioUrl: '', durationSeconds: 0, publishedAt: new Date(), rssGuid: `weekly-global-${Date.now()}` },
          { showType: 'weekly_vertical', title: `Weekly Vertical ${now}`, description: 'Weekly vertical digest', audioUrl: '', durationSeconds: 0, publishedAt: new Date(), rssGuid: `weekly-vertical-${Date.now()}` },
          { showType: 'weekly_local', title: `Weekly Local ${now}`, description: 'Weekly local digest', audioUrl: '', durationSeconds: 0, publishedAt: new Date(), rssGuid: `weekly-local-${Date.now()}` }
        ]
      });

      await log('weekly_digest_queue', 'processed', { date: now });
    },
    { connection }
  );

  // Kick off nightly/background loops when workers boot, deduplicated by stable job IDs.
  const bootstrapQueueMap = {
    source_reputation_queue: sourceReputationQueue,
    personalization_queue: personalizationQueue
  } as const;
  for (const job of getBootstrapJobs()) {
    void bootstrapQueueMap[job.queueName].add(job.name, job.data, { jobId: job.jobId });
  }

  return [
    ingestWorker,
    canonicalizeWorker,
    dedupWorker,
    summarizeWorker,
    evaluationWorker,
    rankWorker,
    sourceReputationWorker,
    personalizationWorker,
    experimentEvalWorker,
    scriptWorker,
    ttsWorker,
    rssPublishWorker,
    weeklyDigestWorker
  ];
}
